language: generic

git:
  depth: 1

matrix:
  include:
    - os: osx
      osx_image: xcode8

before_install:
  - mv $TRAVIS_BUILD_DIR ~/.yadr

install:
  - cd ~/.yadr && rake install

before_script:
  - zsh # starting a zsh session

script:
  - ./test/install-smoke-test.sh
